language: java
jdk:
  - oraclejdk7
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
git:
  depth: 3
branches:
  only:
    - master
    - /^DD-.*$/
script:
    - ./gradlew check
    - ./gradlew assemble
    - ./gradlew :desktop:test
